### ISSUE TITLE
Multiple users - Packet sent failed

### ISSUE THREAD

**Issue by ravenadsl** [raspi/WinLLDPService#10]
- [x] Bug report
  - [ ] Request for enhancement

### Used version of operating system

> Windows Server 2012 R2 Standard + Datacenter  

### In case of bug report: Is machine connected to Active Directory?

 - [x] Yes, Server 2102 R2 AD 
 
### In case of bug report: Version the issue has been seen with

> WinLLDPService 16.12.22.1802 (x64)

### In case of bug report: Expected behaviour you didn't see
Attach possible log(s) and screenshot(s).

>`Packet sent failed: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at WinLLDPService.WinLLDP.Run()
   at WinLLDPService.WinLLDPService.SendPacket(Object source, ElapsedEventArgs ea)`

### In case of bug report: Unexpected behaviour you saw

> Unable to control service (Stop or restart), no information passed to switch, Event written to Event log every 10 minuets with the above error message. 

### In case of bug report: Steps to reproduce the problem

> Install WinPCap, Install WinLLDPService, Start Service. have two users with sessions open on the machine... via RDP or RDP and console. 

### In case of bug report: Additional details
> This problem is caused by having multiple users logged into the machine at the same time. I believe the problem may be at Line 68 of Base.cs " users.Sort(); " there are no issues if there is no users or one user on the system. issue returns when a second user session is started.

**Comment by ahohenadel** [comment]
I am also having this issue.

**Comment by raspi** [comment]
https://github.com/raspi/WinLLDPService/releases/tag/v17.2.9.2046
